---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    volumes:
      - ./data:/config
      - /media/username/New Volume/Torrent/Dizi:/tv
      - /home/username/Videos/Dizi:/tv2
      - /media/username/New Volume/Torrent/downloads:/downloads
      - /home/username/Videos/downloads:/downloads2
    ports:
      - 8989:8989
    restart: unless-stopped
