---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    volumes:
      - ./data:/config
      - /media/username/New Volume/Torrent/Film:/movies
      - /home/username/Videos/Film:/movies2
      - /media/username/New Volume/Torrent/downloads:/downloads
      - /home/username/Videos/downloads:/downloads2
    ports:
      - 7878:7878
    restart: unless-stopped
