# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Admin:
    - Router:
        icon: router.png
        href: http://192.168.1.1/

    - Portainer:
        icon: portainer.png
        widget:
          type: portainer
          fields: ["running", "stopped", "total"]
          url: https://portainer.user.duckdns.org
          env: 2
          key: 
        href: https://portainer.user.duckdns.org
        description: Web UI for Docker

    - Nginx Proxy Manager:
        icon: nginx-proxy-manager.png
        href: https://user.duckdns.org
        description: SSL certificates or something

    - Pi-hole:
        icon: pi-hole.png
        href: https://pihole.user.duckdns.org/admin
        description: Ad Blocker

- Media:
    - Plex:
        icon: plex.png
        widget:
          type: plex
          fields: ["streams", "albums", "movies", "tv"]
          url: https://plex.user.duckdns.org
          key: 
        href: https://plex.user.duckdns.org
        description: Media Server

    - Overseerr:
        icon: overseerr.png
        widget:
          type: overseerr
          fields: ["pending", "approved", "processing"]
          url: https://overseerr.user.duckdns.org
          key: 
        href: https://overseerr.user.duckdns.org
        description: Media Requests

    - Radarr:
        icon: radarr.png
        widget:
          type: radarr
          fields: ["wanted","missing","queued","movies"]
          url: https://radarr.user.duckdns.org
          key: 
        href: https://radarr.user.duckdns.org
        description: Movies

    - Sonarr:
        icon: sonarr.png
        widget:
          type: sonarr
          fields: ["series", "wanted","queued"]
          url: https://sonarr.user.duckdns.org
          key: 
        href: https://sonarr.user.duckdns.org
        description: Shows

    - Bazarr:
        icon: bazarr.png
        widget:
          type: bazarr
          fields: ["missingEpisodes", "missingMovies"]
          url: https://bazarr.user.duckdns.org
          key: 
        href: http://bazarr.user.duckdns.org
        description: Subtitles

- Downloaders:
    - MeTube:
        icon: youtube-dl.png
        href: https://metube.user.duckdns.org/
        description: Youtube Downloader

- Archive:
    - Linkwarden:
        icon: linkwarden.png
        widget:
          type: linkwarden
          fields: ["links"]
          url: https://linkwarden.user.duckdns.org
          key: 
          href: https://linkwarden.user.duckdns.org
        description: Bookmark Manager

    - Mealie:
        icon: mealie.png
        widget:
          type: mealie
          fields: ["recipes"]
          url: https://mealie.user.duckdns.org
          key: 
          version: 2
        href: https://mealie.user.duckdns.org/
        description: Recipe Manager
